### ISSUE TITLE
Add 1 or 2 more Fun Calorie Facts

### ISSUE THREAD

**Issue by sam-g99** [sam-g99/Calorie-Burn-Calculator#1]
Looking for someone to add 1 or 2 more fun calorie facts to the fun fact list in calburned.js which starts on line 116. Happy hacktoberfest :) (first come first served)

**Comment by AndroidonEarth** [comment]
I have a couple I can add :)

**Comment by sam-g99** [comment]
Sounds good!

**Comment by rafiudd** [comment]
it's the issue still opened ?

**Comment by sam-g99** [comment]
> it's the issue still opened ?

You can add 1. But that's all once you two make your pull request I'll officially close this issue.
