### ISSUE TITLE
Hide the sun when in dark mode.

### ISSUE THREAD

**Issue by sam-g99** [sam-g99/Calorie-Burn-Calculator#6]
The sun doesn't belong when it's night time. Can someone hide the sun icon on the top right when dark mode is activated? If you're feeling like going the extra mile add a moon in it's place. Look at line 103 in calburned.js(where the toggle logic is) and line 612 in css (where the dark theme css is).

**Comment by brethubbard** [comment]
Can I take this one?

**Comment by sam-g99** [comment]
> Can I take this one?

All yours. Also line 27 in index html is the toggle container. Much appreciated :)

**Comment by Iamshankhadeep** [comment]
Can I take this also?

**Comment by sam-g99** [comment]
> Can I take this also?

Actually sure you can make the Pull Request.
