### ISSUE TITLE
Add alert for under 10 pounds

### ISSUE THREAD

**Issue by sam-g99** [sam-g99/Calorie-Burn-Calculator#7]
Right now if you go to the home page there's no alert to let users know they need to enter a weight above 10 pounds. Can you add an alert for it? A simple alert() will do or maybe you want to do something fancy. Anyone can make a pull request for this. I'll pick the best one :) (calburned.js line 77)

**Comment by punndcoder28** [comment]
Hey. Can I take up this issue?

**Comment by sam-g99** [comment]
Yeah go ahead!

**Comment by leodalmacio** [comment]
Can I also take this one?
